### ISSUE TITLE
Multi-Module Gradle Support

### ISSUE THREAD

**Issue by ErickSumargo** [google/secrets-gradle-plugin#14]
Hi @arriolac, 
First of all, great plugin! It helps me reduce some boilerplate I used to write for extracting keys stored in e.g., `gradle.properties` file.

But I have a use case where I want the generated keys are visible not limited to `com.android.application` module only, but `com.android.library` modules as well. Even better, I want my keys are generated in a certain module only, but I don't find such abilities in the current plugin version.

Btw, I've made a local workaround for this case. I'd be ready to submit my PR if my requirement is eligible enough treated as a "feature request". Thank you.

**Comment by arriolac** [comment]
Hi @ErickSumargo, I think that's a perfectly valid use case. Before submitting a pull request, can you comment here if that creates any API changes (if any)?

**Comment by ErickSumargo** [comment]
Absolutely no changes to the existing core logic API @arriolac. But some extension are needed.

In detail, literally I only need to expose `LibraryExtension` type and have the `SecretPlugin` read the libraryVariants from it with the same closure inject logic.

**Comment by arriolac** [comment]
Gotcha. Feel free to send a PR and we can go it from there. Thanks!
