### ISSUE TITLE
Creating problems with Github Actions

### ISSUE THREAD

**Issue by bhavinmdesai** [google/secrets-gradle-plugin#30]
When I use this plugin in my app and if I have Github Action setup, it ends up with following error:

```
* What went wrong:
A problem occurred configuring project ':app'.
> java.io.FileNotFoundException: The file '/home/runner/work/AppName/AppName/local.properties' could not be found
```

**Comment by arriolac** [comment]
That's because the `local.properties` file is not checked in the repository (as it shouldn't). I recommend creating a defaults file with the keys used by your app but stub values that you can check in the repository. See [configuration options](https://github.com/google/secrets-gradle-plugin#configuration-options). This strategy is used by the sample app in this repository.

**Comment by bhavinmdesai** [comment]
I was managed to resolve the issue by adding `gradle.properties` as `defaultPropertiesFileName`. Don't you think that it should be managed by the library?

**Comment by arriolac** [comment]
I don't think it should be the responsibility of the plugin—the required keys for an app to be compiled must be provided somehow. Do you have a proposed solution?

Relates to #6

**Comment by bhavinmdesai** [comment]
I was thinking that `gradle.properties` is a very basic file that used to have a lot of project related keys. I don't think anyone stores secrets in that file.

What if I have project related keys into multiple files? How does this plugin support it?

**Comment by arriolac** [comment]
Multiple files are not currently supported by the plugin. It can be done by providing a list of file names in the configuration block—if it's a common enough use case for folks, it can be added.

**Comment by bhavinmdesai** [comment]
In my case, I need to exclude all the properties from `gradle.properties` file as they are required during the build process (and I don't want them to be created in BuildConfig) but looks like the plugin is excluding the file if it is not specified as `defaultPropertiesFileName`.

Is there a better way currently than adding 5-6 keys to the ignore list?

**Comment by arriolac** [comment]
The way to avoid that is to add all your key/values that you want injected in a file separate from `gradle.properties` and use it under `defaultPropertiesFileName`.

**Comment by arriolac** [comment]
Closing this, please see my comment above as a way to resolve this issue. If another behavior is desired, please propose a solution and file an FR. Thanks!
