### ISSUE TITLE
Unable to read values

### ISSUE THREAD

**Issue by huzaifaaak** [google/secrets-gradle-plugin#34]
During build this error is thrown: 
`Attribute meta-data#com.google.android.geo.API_KEY@value at AndroidManifest.xml:17:9-35 requires a placeholder substitution but no value for <GMP_KEY> is provided.`

If I add a sample placeholder in my default config the app seems to build fine but the keys are not read in manifest: 

Build.gradle(app): 

    defaultConfig {
        applicationId "com.projID"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 3
        versionName "0.1"
        multiDexEnabled true
        manifestPlaceholders=[GMP_KEY: "Google Maps", googleMapApiKey: ""]
    }

Build.gradle(root):

    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29

        googlePlayServicesVersion = "17.0.0"
        androidMapsUtilsVersion="2.2.5"
    }

I have tried manually adding the keys in manifest and that works fine. 
I am running this with React-Native

**Comment by huzaifaaak** [comment]
Donwgrade to `com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:1.2.0` fixed for me.

**Comment by arriolac** [comment]
Plugin 1.3.0 should work. What version of AGP are you using?

**Comment by huzaifaaak** [comment]
I am using 4.2.0  ` classpath('com.android.tools.build:gradle:4.2.0')`
