### ISSUE TITLE
Key is visible in AndroidManifest after performing profiling on APK 

### ISSUE THREAD

**Issue by bhushanpd** [google/secrets-gradle-plugin#35]
Hi,

 We are having below configuration in our project.
gradle = 4.2.1
Kotlin version = 1.5.0

 We tried to use this plugin to hide the google map key. We followed below mentioned steps but still when we perform profile on APK, we can see key stored in the local properties as it is inside Manifest metadata. Kindly let us know if we are missing any step.

**1. Added to root-level build.gradle** 
buildscript {
    dependencies {
        // ...
        classpath "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:1.3.0"
    }
}

**2. Added to app-level build.gradle to the plugin element**
   id 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin'

**3. Sync gradle**

**4. Added to local.properties**
MAPS_API_KEY=Az....

**5. In Android Manifest.xml added**
<meta-data
    android:name="com.google.android.geo.API_KEY"
    android:value="${MAPS_API_KEY}" />

**6. Created build in Release Mode**

We we open the build in profile, we can see "${MAPS_API_KEY}" in AndroidManifest is replaced with the actual key. Kindly let us know if anything missing to hide the map key.

**Comment by arriolac** [comment]
HI @bhushanpd, it is still possible to view strings in that manner. As mentioned in the README of this repo:

> DISCLAIMER: This plugin is primarily for hiding your keys from version control. Since your key is part of the static binary, your API keys are still recoverable by decompiling an APK. So, securing your key using other measures like adding restrictions (if possible) are recommended.

Unfortunately there is no way around this given the current mechanism for passing in keys so [restrictions](https://developers.google.com/maps/api-security-best-practices#application-restriction%22) should still be applied to your API key
