### ISSUE TITLE
Is not reading the key values 

### ISSUE THREAD

**Issue by johnjeremih** [google/secrets-gradle-plugin#37]
I added as is displayed in the documentation and doesn't work
![image](https://user-images.githubusercontent.com/4177453/127576795-a73c7cea-ebca-4564-b6ba-0f3aea3a663e.png)
![image](https://user-images.githubusercontent.com/4177453/127576826-7e67e85d-c12f-4307-b9ca-537b4d25bebb.png)

**Comment by arriolac** [comment]
Can you provide details on the error you are seeing (if any)?

**Comment by johnjeremih** [comment]
`/Users/johndelacruz/Documents/development/android/kotlin/seattap-android/app/src/main/AndroidManifest.xml:64:13-51 Error:
	Attribute meta-data#com.google.android.geo.API_KEY@value at AndroidManifest.xml:64:13-51 requires a placeholder substitution but no value for <GOOGLE_MAPS_API_KEY> is provided.
/Users/johndelacruz/Documents/development/android/kotlin/seattap-android/app/src/main/AndroidManifest.xml Error:
	Validation failed, exiting`

**Comment by arriolac** [comment]
The key `GOOGLE_MAPS_API_KEY` should be in your `local.properties` file, not `gradle.properties` (unless you explicitly configured the plugin to read from that file instead).

**Comment by johnjeremih** [comment]
Thank you!

**Comment by johnjeremih** [comment]
For some reason when adding the variables like this ${GOOGLE_MAPS_KEY} on the value.
![image](https://user-images.githubusercontent.com/4177453/127684198-f53d5b48-eac1-4d1b-9b1d-9c52ba34c52f.png)

The program compiles, but it gives me this error. 
![image](https://user-images.githubusercontent.com/4177453/127684491-962a3704-3e45-41d6-b235-ec85189fcf5d.png)

**Comment by arriolac** [comment]
Hi @johnjeremih, the issue you pasted is unrelated to this library. Looks like you need to request those permissions in your app to remove that warning. Closing this.

**Comment by johnjeremih** [comment]
@arriolac It is related because it is happening in two of my apps. Please see the image below. I remove the variable the problem disappears. I just added a video.

Uploading Screen Recording 2021-08-09 at 2.37.51 PM.mov… 

![image](https://user-images.githubusercontent.com/4177453/128756555-75d8f769-b755-462e-838f-e4552e6d4b1c.png)

**Comment by arriolac** [comment]
Perhaps an issue with Android Studio? This plugin doesn't modify app permissions so I'm having trouble trying to draw a correlation between the two.
