### ISSUE TITLE
Error while updating dependency to 2.0.0

### ISSUE THREAD

**Issue by bhavinmdesai** [google/secrets-gradle-plugin#42]
After I update the dependency version from `1.3.0` to `2.0.0`, I am getting following error after Gradle sync

>Unable to load class 'com.android.build.api.variant.AndroidComponentsExtension'.
>
>This is an unexpected error. Please file a bug containing the idea.log file.

Additional information:
- Gradle build tool version: 4.2.2
- Gradle wrapper: 7.0.2

**Comment by nsekhar90** [comment]
having the same issue

**Comment by arriolac** [comment]
What version of AGP are you using? 2.0.0 requires AGP version 7.0.0

In your project-level `build.gradle` file:
```
buildscript {
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.0"
    }
}
```

**Comment by arriolac** [comment]
@bhavinmdesai and @nsekhar90 following up, is this still an issue for both of you?

**Comment by bhavinmdesai** [comment]
@arriolac Tried on `7.0.2` and it is working as expected.
