### ISSUE TITLE
java.lang.NoClassDefFoundError: com/android/build/api/variant/AndroidComponentsExtension

### ISSUE THREAD

**Issue by johnjeremih** [google/secrets-gradle-plugin#48]
I'm getting this error on version 2.0.0. Version 1.3.0 works fine except when adding it as a variable on the manifest.

![image](https://user-images.githubusercontent.com/4177453/151244166-f7de650d-9a77-4a17-acf9-4259ce78770e.png)

![image](https://user-images.githubusercontent.com/4177453/151244329-0cfbae2d-bb6b-4aa9-b06e-47a6bcb59bc1.png)
  // Secret key plugin
        classpath("com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:2.0.0")

**Comment by arriolac** [comment]
What version of AGP are you using? Note that the 2.0.0 plugin requires AGP 7.0.0.
