### ISSUE TITLE
Merging error + problem in adding API key to the project

### ISSUE THREAD

**Issue by adi-andro** [google/secrets-gradle-plugin#49]
I followed this guide still facing problem in adding API key to the project. I have successfully installed the secrects gradle plugin. But when i open this local.properties file it does not allow to make any changes. The contents of the file are not as mentioned in the guide.
![local properties](https://user-images.githubusercontent.com/98539440/151390482-e802bfab-6dac-4982-999d-e4a91a48bc03.png)

Merging error in AndroidManifest.xml
![manifest erroe](https://user-images.githubusercontent.com/98539440/151390620-51f7b1ab-9e44-492b-9668-5f088fbc3793.png)

I'm stuck in step 4 of the process mentioned below.
![add api key steps](https://user-images.githubusercontent.com/98539440/151392101-0a305f99-9e26-41b6-85f7-833b2864d995.png)

Help please

**Comment by arriolac** [comment]
@adi-andro What is preventing you from editing the local.properties file? That file is meant to be edited/added to and you should be able to add a new key/value definition as described in the documentation.

**Comment by adi-andro** [comment]
It shows these error.

![problem](https://user-images.githubusercontent.com/98539440/151419031-c95bac30-186e-4276-b3be-67ae1df1d76c.png)

**Comment by arriolac** [comment]
That looks fine to me although you removed the `sdk.dir=...` definition which should still be defined in your local.properties file.

**Comment by jamesvanhallen** [comment]
hello everyone, I have the same issue:
property googleMapApiKey from local.properties file is unused
google map isn't displayed

Gradle 7.2
Kotlin:       1.5.21
Groovy:       3.0.8
JVM:          11.0.14 (Amazon.com Inc. 11.0.14+9-LTS)
OS:           Mac OS X 11.6.1 x86_64

**Comment by arriolac** [comment]
Is this still an issue @adi-andro ?

**Comment by arriolac** [comment]
Closing this as I have not heard back. Feel free to reopen will more info if this is still an issue.
