### ISSUE TITLE
How would you recommend to support release compilation into a CI/CD server?

### ISSUE THREAD

**Issue by gerardoepitacio** [google/secrets-gradle-plugin#53]
An android application may be compiled in an external server without local.properties present, due the host only download the current state of the project, how do you recommend to keep the keys secure and at the same time support this kind of compilations?.

**Comment by arriolac** [comment]
It depends on what CI/CD you use. For example, GitHub has support for [encrypted secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets)—you can add your key there and have a step to read that secret into the server's `local.properties` file.

**Comment by gerardoepitacio** [comment]
We use Azure DevOps to compile, I'll try this approach which will write a file for every compilation.
