### ISSUE TITLE
File leak in `loadPropertiesFile()` function within Extensions.kt

### ISSUE THREAD

**Issue by pablobaxter** [google/secrets-gradle-plugin#81]
This line causes a file leak that opens the given file each time a Gradle build is configured.

https://github.com/google/secrets-gradle-plugin/blob/16b9e729eb920017c00211e1c59837d7756f08cf/secrets-gradle-plugin/src/main/java/com/google/android/libraries/mapsplatform/secrets_gradle_plugin/Extensions.kt#L53C1-L53C50

**Comment by wangela** [comment]
Thanks for reporting the issue and providing a fix, @pablobaxter!
